#!/bin/bash

# Source files
FILES=(
  "src/mod/lex.sig"
  "src/mod/lex.sml"
  "src/omega-reg.sig"
  "src/omega-reg.sml"
  "src/nba.sig"
  "src/nba.sml"
)

# Temporary FIFO
FIFO=$(mktemp -u)
mkfifo "$FIFO"

# Feed use commands into FIFO, then attach terminal input
{
  for file in "${FILES[@]}"; do
    echo "use \"$file\";"
  done
  # keep REPL open by passing control to keyboard
  cat /dev/tty
} > "$FIFO" &

# Start Forlan REPL reading from FIFO
forlan < "$FIFO"

# Clean up
rm "$FIFO"

# # Source files
# FILES=(
#   "src/omega-reg.sig"
#   "src/omega-reg.sml"
#   "src/nba.sig"
#   "src/nba.sml"
# )

# # Temporary files and FIFO
# FIFO=$(mktemp -u)
# mkfifo "$FIFO"
# TMP_OUTPUT=$(mktemp)

# # Feed use commands into FIFO, then attach terminal input
# {
#   for file in "${FILES[@]}"; do
#     echo "use \"$file\";"
#   done
#   # small marker to detect when file loading is done
#   echo 'val _ = print "[[READY]]\n";'
#   cat /dev/tty
# } > "$FIFO" &

# # Start Forlan REPL, redirecting output to a temp file
# forlan < "$FIFO" > "$TMP_OUTPUT" 2>&1 &

# FORLAN_PID=$!

# # Wait until the marker [[READY]] appears
# while ! grep -q "\[\[READY\]\]" "$TMP_OUTPUT"; do
#   sleep 0.1
# done

# # After loading is done, print banner manually
# printf "ω-Forlan Version 1.0 (based on Forlan Version 4.15)\n"
# printf "val it = () : unit\n"
# printf "%s" "- "

# # Now start tailing output normally
# tail -n 0 -f "$TMP_OUTPUT" &

# # Wait for Forlan to exit
# wait $FORLAN_PID

# # Clean up
# rm "$FIFO" "$TMP_OUTPUT"